### PR TITLE
chore: add GitHub Actions CI

### PR DESCRIPTION
**Pull request by Nikolasel**
This pull request solves issue #32. The only difference is that my solution uses GitHub Actions and not Travis CI.

### CODE REVIEW

**Comment by monperrus** [comment]
nice! thanks a lot! is that possible to have both Github Actions and Travis CI?

**Comment by Nikolasel** [comment]
Both should be possible at the same time. Probably only a corresponding .travis.yml is needed. This has the downside that two CI files must be maintained. Also if I remember it correctly every fork must also register at Travis CI to do CI with Travis.

**Comment by monperrus** [comment]
Thanks a lot!

**Comment by monperrus** [comment]
Nikolas, do you think it's possible o make continuous delivery too with Github Actions? push a new release on Github at each commit on master?

**Comment by Nikolasel** [comment]
Yes, continuous delivery is also possible with Github Actions. I would recommend to do snapshot deployment and release deployment. On every push to the master branch, a snapshot deployment happens (e.g., the generated version is 0.7-Snapshot). The snapshot can be overwritten on the next push. The release deployment can work like this: @monperrus creates a new release in Github and the continuous delivery job changes the version to release version (e.g, 0.7-Snapshot -> 0.7) and pushes the build to the newly generated Github release and after that changes the version to the next snapshot version (e.g., 0.8-Snapshot).
This all assumes that the location of the release file is changed. So the releases are not more in the repository instead they are in Github releases.

**Comment by monperrus** [comment]
> So the releases are not more in the repository instead they are in Github releases.

Yes, which is even better!

> I would recommend to do snapshot deployment and release deployment.

For such a small project, it's almost overkill. One release per commit with increased minor version
is simpler to handle and can be considered enough

**Pull request merged**
