### PR TITLE
Addresses #10, Copy page number area to a new text area in the same position

### LINKED ISSUE #10: Slide numbers aren't preserved
Hi. Firstoff, this is a great extension and works (since 0.40) almost entirely as expected. There is just one issue: the slide numbers aren't preserved and will go up with any bullet point appearing.
Anyways, I can understand if fixing that issue is out of scope for this project, but thanks for considering it, and most of all thanks for this great extension.

### PR DESCRIPTION
**Pull request by hylkevds**
I did a bit of hacking trying to fix #10. My first ooBasic :)
It:
- searches the master slide of each slide for a shape of type SlideNumberShape. Changing the text of this shape would change it in every slide, so that's no option
- creates a new TextShape on the current slide. I did not find a way to copy the SlideNumberShape from the master to the slide
- give the new shape the same style, position & size as the SlideNumberShape.
- sets the TextVerticalAdjust to be the same as the SlideNumberShape. For some reason this is not part of the style
- sets the text of the new shape to be "currentSlide / numberOfSlides". This probably needs to be changed to some analysis of the original text to mimic that

Since it does this before the animation is expanded, all expanded pages will get the same page number.
For this to work properly, the SlideNumberShape must not have custom formatting other than the TextVerticalAdjust. Only formatting from the style is copied to the new shape. The style should also have a non-transparent background so it hides the original number.

### CODE REVIEW

**Comment by monperrus** [comment]
really cool! since we have no CI, anybody to try the change?

**Comment by hylkevds** [comment]
I've moved the code to a function, and made it only run when the slide has a page number. It now also turns off the automatic page number, so it's no longer an issue of the page number shape has a transparent background.

I also noticed that page numbers were wrong in the index of the pdf. Since only the expanded pages had their name changed, all other pages got the wrong generated name. But names are treated very strangely. It's impossible to manually name a slide `Slide XX`. Auto-names are in the form of `pageXX`.
In the end I just rename all pages that seem to have an auto generate name to `Slide: XX`. With a `:` in the name, since otherwise the rename is refused.

**Comment by monperrus** [comment]
New Github actions CI says OK (big kudos to @Nikolasel), merging.

Thanks for the fix!

**Comment by Nikolasel** [comment]
Improvement for the CI: the test ODP file should also contain a page number field in the master slide.

**Pull request merged**
