### PR TITLE
This should fix #13 but may have unknown side effects

### LINKED ISSUE #13: BASIC runtime error. Property or method not found: AttributeName.
Errors in this function it seems:

' checks if the given animation node changes a shape's visibility
function isVisibilityAnimation(animNode as Object) as Boolean
    isVisibilityAnimation = HasUnoInterfaces(animNode, ANIMSET) and _
                            (animNode.AttributeName = VISATTR)
end function

I can send slides if desired.

### PR DESCRIPTION
**Pull request by link458**
Added some error state handling and catching.

(works for my test case at least)

Ignore white spaces to not be confused - I only changed like 6 lines. I am pretty sure there is a better way to fix it but can't dig deeper into it for now and wanted to provide a solution for the time being.

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot! Could you update the PR to have a clear diff with only the 6 changed lines?

**Comment by monperrus** [comment]
ping?

**Comment by rhaschke** [comment]
This seems to be overly complex.
For me, it was only necessary to ignore errors in `isVisibilityAnimation()`. See #27 for an alternative.

**Comment by monperrus** [comment]
closed per #27

**Pull request closed without merging**
