### PR TITLE
feat: add support for NotebookBar

### LINKED ISSUE #41: Support for Notebookbar
Once again, thanks for your work!
It would be great if the option to trigger ExpandAnimations would not only be found under Tools>>Add-ons>>Expand animations but also in the NotebookBar "Extension"-Tab. Some further information regarding this [is provided here](https://wiki.documentfoundation.org/Development/NotebookBar/Extensions).

### PR DESCRIPTION
**Pull request by errotu**
Fixes #41

### CODE REVIEW

**Comment by monperrus** [comment]
LGTM. Does it work as expected?

**Comment by errotu** [comment]
Works as expected. Just the context value seems to be ignored. The icon is also displayed in Writer or Calc. This seems like a LO bug to me.

Here's a screenshot:
grafik

**Comment by errotu** [comment]
I just checked: The example of the writer2epub-Extension, which is recommended [in the wiki](https://wiki.documentfoundation.org/Development/NotebookBar/Extensions#Modified_Extensions), ignores the context value as well. Therefore, it seems like this is an issue on the side of LO, not the extension.

**Comment by monperrus** [comment]
Thanks for the explanation. So if you undraft the PR, I can merge it.

**Comment by monperrus** [comment]
Thanks!

**Pull request merged**
