### PR TITLE
#35: Adds continuous delivery to Github Release

### PR DESCRIPTION
**Pull request by Nikolasel**
I merged CI and CD into one workflow to start CD only if CI was successful.

### CODE REVIEW

**Comment by monperrus** [comment]
Really nice!

Do I need to configure secrets somewhere before merging?

**Comment by Nikolasel** [comment]
Currently, the CD only pushes the to GitHub releases. The secret for GitHub is automatically added to GitHub Actions. So no further keys are required.
If you want to add the LibreOffice extension server to your CD then additional keys are required. But I haven't looked at the LibreOffice extension server so I don't have further information.

**Comment by monperrus** [comment]
Great, let's give it a try! Thanks a lot.

**Comment by monperrus** [comment]
follow-up #38

**Comment by monperrus** [comment]
Hurray, it works! https://github.com/monperrus/ExpandAnimations/releases/tag/0.7

**Comment by monperrus** [comment]
FYI, CD was broken, fixed by adding 
```
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
```
in https://github.com/monperrus/ExpandAnimations/commit/08ab89428b4599d23625e560c3cc79481aaf79c4

**Pull request merged**
